// Every element the app touches, looked up once and typed. A missing id fails loudly at start-up
// (with its name) instead of surfacing later as "cannot read properties of null".

function el<T extends HTMLElement>(id: string): T {
  const found = document.getElementById(id);
  if (!found) throw new Error(`index.html is missing #${id}`);
  return found as T;
}

export const dom = {
  acneSection: el<HTMLElement>("acneSection"),
  acneSelection: el<HTMLElement>("acneSelection"),
  acneSlider: el<HTMLInputElement>("acneSlider"),
  acneStatus: el<HTMLElement>("acneStatus"),
  acneValue: el<HTMLElement>("acneValue"),
  scarsSlider: el<HTMLInputElement>("scarsSlider"),
  scarsValue: el<HTMLElement>("scarsValue"),
  poresSlider: el<HTMLInputElement>("poresSlider"),
  poresValue: el<HTMLElement>("poresValue"),
  backHomeBtn: el<HTMLButtonElement>("backHomeBtn"),
  beforeBtn: el<HTMLButtonElement>("beforeBtn"),
  blendSlider: el<HTMLInputElement>("blendSlider"),
  blendValue: el<HTMLElement>("blendValue"),
  brightnessSlider: el<HTMLInputElement>("brightnessSlider"),
  brightnessValue: el<HTMLElement>("brightnessValue"),
  cameraBtn: el<HTMLButtonElement>("cameraBtn"),
  chooseLipsBtn: el<HTMLButtonElement>("chooseLipsBtn"),
  chooseWrinklesBtn: el<HTMLButtonElement>("chooseWrinklesBtn"),
  chooseAcneBtn: el<HTMLButtonElement>("chooseAcneBtn"),
  wrinklesSampleBtn: el<HTMLButtonElement>("wrinklesSampleBtn"),
  acneSampleBtn: el<HTMLButtonElement>("acneSampleBtn"),
  chooseSkinBtn: el<HTMLButtonElement>("chooseSkinBtn"),
  colorSection: el<HTMLElement>("colorSection"),
  colorSlider: el<HTMLInputElement>("colorSlider"),
  colorValue: el<HTMLElement>("colorValue"),
  compareSection: el<HTMLElement>("compareSection"),
  faceBadge: el<HTMLElement>("faceBadge"),
  fileInput: el<HTMLInputElement>("fileInput"),
  fileInputOverlay: el<HTMLInputElement>("fileInputOverlay"),
  lipDebug: el<HTMLInputElement>("lipDebug"),
  lipSlider: el<HTMLInputElement>("lipSlider"),
  lipValue: el<HTMLElement>("lipValue"),
  lipsSection: el<HTMLElement>("lipsSection"),
  liveBadge: el<HTMLElement>("liveBadge"),
  moduleEyebrow: el<HTMLElement>("moduleEyebrow"),
  moduleHeader: el<HTMLElement>("moduleHeader"),
  moduleHome: el<HTMLElement>("moduleHome"),
  moduleTitle: el<HTMLElement>("moduleTitle"),
  overlay: el<HTMLElement>("overlay"),
  perfBadge: el<HTMLElement>("perfBadge"),
  photo: el<HTMLImageElement>("photo"),
  resetBtn: el<HTMLButtonElement>("resetBtn"),
  resetSection: el<HTMLElement>("resetSection"),
  sampleBtn: el<HTMLButtonElement>("sampleBtn"),
  sampleBtnOverlay: el<HTMLButtonElement>("sampleBtnOverlay"),
  skinDebug: el<HTMLInputElement>("skinDebug"),
  skinDebugSection: el<HTMLElement>("skinDebugSection"),
  skinSection: el<HTMLElement>("skinSection"),
  sourceBadge: el<HTMLElement>("sourceBadge"),
  stage: el<HTMLCanvasElement>("stage"),
  stageWrap: el<HTMLElement>("stageWrap"),
  startBtn: el<HTMLButtonElement>("startBtn"),
  verticalSlider: el<HTMLInputElement>("verticalSlider"),
  verticalValue: el<HTMLElement>("verticalValue"),
  video: el<HTMLVideoElement>("video"),
  wrinklesSection: el<HTMLElement>("wrinklesSection"),
  wrinklesSelection: el<HTMLElement>("wrinklesSelection"),
  wrinklesSlider: el<HTMLInputElement>("wrinklesSlider"),
  wrinklesStatus: el<HTMLElement>("wrinklesStatus"),
  wrinklesValue: el<HTMLElement>("wrinklesValue"),
  // Groups selected by class / attribute rather than id.
  lipPresetButtons: [...document.querySelectorAll<HTMLButtonElement>(".preset-btn")],
  shadeButtons: [...document.querySelectorAll<HTMLButtonElement>(".shade-btn")],
  finishButtons: [...document.querySelectorAll<HTMLButtonElement>("[data-finish]")],
  acnePresetButtons: [...document.querySelectorAll<HTMLButtonElement>("[data-acne-preset]")],
  wrinklesPresetButtons: [...document.querySelectorAll<HTMLButtonElement>("[data-wrinkles-preset]")],
};
